replicaCount: 1
hostAliases:
  - ip: "172.18.0.3"
    hostnames:
      - "iam.nexus-bank.io"
      - "fynams.sandbox.nexus-bank.io"
image:
  repository: nexusbank/core-banking-api
  tag: "latest"
  pullPolicy: Always

env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0
  KEYCLOAK_URL: "https://iam.nexus-bank.io/auth"
  KEYCLOAK_REALM: "customer_eu"
  KEYCLOAK_CLIENT_ID: "selfService-app-oidc"
  KEYCLOAK_CLIENT_SECRET: "x9OINBdsQrquZyn6jx35slRwKN8QpvsK"
  SUBJECT_ISSUER: "keycloak-oidc"
  KEYCLOAK_ADMIN_CLIENT_ID: "selfService-registration-app-oidc"
  KEYCLOAK_ADMIN_CLIENT_SECRET: "JRzOURegA1kwtT6mXC4uasSb4zGNmWvH"
  KEYCLOAK_FINERACT_REALM: "internal"
  KEYCLOAK_FINERACT_CLIENT_ID: "selfService-app-oidc"
  KEYCLOAK_FINERACT_CLIENT_SECRET: "PW9Vn1dxI2VS8V6fsyyZvgnkoPtWbp10"
  KEYCLOAK_FINERACT_USERNAME: "mifos"
  KEYCLOAK_FINERACT_PASSWORD: "password"
  FINERACT_BASE_URL: "https://fynams.sandbox.nexus-bank.io"
  FINERACT_BASE_PATH: "/fineract-provider/api/v1"
  FINERACT_TENANT: "default"
  SAVING_PRODUCT_ID: 1
  OFFICE_ID: 2
  STRIPE_WEBHOOK_SECRET: sk_test_51SwJKzE0sjkbbrOPBlBY07xkIGHKL0vm4Opg4BEDPVNgAyq6nzLfK713upqTIvpPvQJPNgmWz7Ahj4iHbwzxzhI200jiUVtgPX
  STRIPE_SECRET_KEY: pk_test_51SwJKzE0sjkbbrOPeNYeq6hdhllCLRkO95iUvqHEfrLr8wTy4ztYPwYdS0EejH3bSvcQzRV524g3uwHKLjKFQa5i00rLh5y2Qc


extraEnv: |
  - name: NODE_EXTRA_CA_CERTS
    value: /etc/certificate/ca.pem

extraVolumes:
  - name: certificate
    configMap:
      name: ca-config-map
extraVolumeMounts:
  - name: certificate
    mountPath: /etc/certificate
    readOnly: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffers: "416k"
    cert-manager.io/cluster-issuer: nbank
  hosts:
    - host: selfservicefr.sandbox.nexus-bank.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - selfservicefr.sandbox.nexus-bank.io
      secretName: "selfservicefr-tls"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}


livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
