{{- $create := true -}}
{{- if and (hasKey .Values "caConfigMap") (hasKey .Values.caConfigMap "create") -}}
{{- $create = .Values.caConfigMap.create -}}
{{- end -}}
{{- if $create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-config-map
data:
  ca.pem: |-
{{ .Files.Get "certificates/ca.pem" | indent 4 }}
{{- end }}

