{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "produit-api.postgresql.fullname" . }}
  labels:
    {{- include "produit-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "produit-api.name" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
