replicaCount: 1
image:
  repository: nexusbank/subscription-api
  tag: latest
  pullPolicy: Always
env:
  PORT: "8080"
  DISABLE_AUTH: "false"
  KEYCLOAK_ISSUER_URI: "https://iam.dev.sandbox.internal.nbank.fr/auth/realms/internal"
  KEYCLOAK_JWK_SET_URI: "https://iam.dev.sandbox.internal.nbank.fr/auth/realms/internal/protocol/openid-connect/certs"
  DATABASE_URL: "jdbc:h2:file:/data/subscriptions;DB_CLOSE_ON_EXIT=FALSE"
  JPA_DDL_AUTO: update
extraEnv: ""
hostAliases: []
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: false
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: nbank-dev
  hosts:
    - host: subscription-api.api.dev.sandbox.internal.nbank.fr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  storageClass: ""
  mountPath: /data
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  enabled: true
  initialDelaySeconds: 45
  periodSeconds: 15
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
