apiVersion: v1
kind: Service
metadata:
  name: {{ include "card-management-api.fullname" . }}
  labels:
    {{- include "card-management-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "card-management-api.name" . }}
