apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core-banking.fullname" . }}
  labels:
    {{- include "core-banking.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "core-banking.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "core-banking.name" . }}
    spec:
      hostAliases: {{ toYaml .Values.hostAliases | nindent 8 }}
      containers:
        - name: core-banking
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: KEYCLOAK_URL
              value: "{{ .Values.env.KEYCLOAK_URL }}"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.env.KEYCLOAK_REALM }}"
            - name: KEYCLOAK_CLIENT_ID
              value: "{{ .Values.env.KEYCLOAK_CLIENT_ID }}"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "{{ .Values.env.KEYCLOAK_CLIENT_SECRET }}"
            - name: SUBJECT_ISSUER
              value: "{{ .Values.env.SUBJECT_ISSUER }}"
            - name: KEYCLOAK_ADMIN_CLIENT_ID
              value: "{{ .Values.env.KEYCLOAK_ADMIN_CLIENT_ID }}"
            - name: KEYCLOAK_ADMIN_CLIENT_SECRET
              value: "{{ .Values.env.KEYCLOAK_ADMIN_CLIENT_SECRET }}"
            - name: KEYCLOAK_INTERNAL_REALM
              value: "{{ .Values.env.KEYCLOAK_INTERNAL_REALM }}"
            - name: KEYCLOAK_FINERACT_CLIENT_ID
              value: "{{ .Values.env.KEYCLOAK_FINERACT_CLIENT_ID }}"
            - name: KEYCLOAK_FINERACT_CLIENT_SECRET
              value: "{{ .Values.env.KEYCLOAK_FINERACT_CLIENT_SECRET }}"
            - name: KEYCLOAK_FINERACT_USERNAME
              value: "{{ .Values.env.KEYCLOAK_FINERACT_USERNAME }}"
            - name: KEYCLOAK_FINERACT_PASSWORD
              value: "{{ .Values.env.KEYCLOAK_FINERACT_PASSWORD }}"
            - name: FINERACT_BASE_URL
              value: "{{ .Values.env.FINERACT_BASE_URL }}"
            - name: FINERACT_BASE_PATH
              value: "{{ .Values.env.FINERACT_BASE_PATH }}"
            - name: FINERACT_TENANT
              value: "{{ .Values.env.FINERACT_TENANT }}"
            - name: DEFAULT_SAVING_PRODUCT
              value: "{{ .Values.env.DEFAULT_SAVING_PRODUCT }}"
            - name: SAVING_PRODUCTS
              value: '{{ .Values.env.SAVING_PRODUCTS | toJson }}'
            - name: OFFICE_ID
              value: "{{ .Values.env.OFFICE_ID }}"
            - name: SWIFT_BIC
              value: "{{ .Values.env.SWIFT_BIC }}"
            - name: BANK_CODE
              value: "{{ .Values.env.BANK_CODE }}"
            - name: COUNTRY_CODE
              value: "{{ .Values.env.COUNTRY_CODE }}"
            - name: STRIPE_WEBHOOK_SECRET
              value: "{{ .Values.env.STRIPE_WEBHOOK_SECRET }}"
            - name: STRIPE_SECRET_KEY
              value: "{{ .Values.env.STRIPE_SECRET_KEY }}"
              {{- with .Values.extraEnv }}
              {{- tpl . $ | nindent 12 }}
              {{- end }}
          livenessProbe:
            {{- if .Values.livenessProbe.enabled }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            {{- end }}
          readinessProbe:
            {{- if .Values.readinessProbe.enabled }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            {{- end }}
          volumeMounts:
{{- toYaml .Values.extraVolumeMounts | nindent 12 }}
      volumes:
{{- toYaml .Values.extraVolumes | nindent 8 }}

      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
